options:
    resources_mirror:
        type: string
        default: ''
        description: |
            URL from which to fetch resources (e.g., Hadoop binaries) instead of Launchpad.
    hadoop_version:
        type: string
        default: '2.7.1'
        description: |
            Hadoop version
